// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: gm.proto

package in

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GmAddResource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid *uint64 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Res *string `protobuf:"bytes,2,opt,name=res" json:"res,omitempty"`
}

func (x *GmAddResource) Reset() {
	*x = GmAddResource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GmAddResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GmAddResource) ProtoMessage() {}

func (x *GmAddResource) ProtoReflect() protoreflect.Message {
	mi := &file_gm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GmAddResource.ProtoReflect.Descriptor instead.
func (*GmAddResource) Descriptor() ([]byte, []int) {
	return file_gm_proto_rawDescGZIP(), []int{0}
}

func (x *GmAddResource) GetUid() uint64 {
	if x != nil && x.Uid != nil {
		return *x.Uid
	}
	return 0
}

func (x *GmAddResource) GetRes() string {
	if x != nil && x.Res != nil {
		return *x.Res
	}
	return ""
}

type GmUpdateGameRouter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Areas []*GameRouterInfo `protobuf:"bytes,1,rep,name=areas" json:"areas,omitempty"`
}

func (x *GmUpdateGameRouter) Reset() {
	*x = GmUpdateGameRouter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GmUpdateGameRouter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GmUpdateGameRouter) ProtoMessage() {}

func (x *GmUpdateGameRouter) ProtoReflect() protoreflect.Message {
	mi := &file_gm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GmUpdateGameRouter.ProtoReflect.Descriptor instead.
func (*GmUpdateGameRouter) Descriptor() ([]byte, []int) {
	return file_gm_proto_rawDescGZIP(), []int{1}
}

func (x *GmUpdateGameRouter) GetAreas() []*GameRouterInfo {
	if x != nil {
		return x.Areas
	}
	return nil
}

type GameRouterInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AreaId *uint32  `protobuf:"varint,1,opt,name=area_id,json=areaId" json:"area_id,omitempty"`
	BusId  []uint32 `protobuf:"varint,2,rep,name=bus_id,json=busId" json:"bus_id,omitempty"`
}

func (x *GameRouterInfo) Reset() {
	*x = GameRouterInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameRouterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameRouterInfo) ProtoMessage() {}

func (x *GameRouterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameRouterInfo.ProtoReflect.Descriptor instead.
func (*GameRouterInfo) Descriptor() ([]byte, []int) {
	return file_gm_proto_rawDescGZIP(), []int{2}
}

func (x *GameRouterInfo) GetAreaId() uint32 {
	if x != nil && x.AreaId != nil {
		return *x.AreaId
	}
	return 0
}

func (x *GameRouterInfo) GetBusId() []uint32 {
	if x != nil {
		return x.BusId
	}
	return nil
}

var File_gm_proto protoreflect.FileDescriptor

var file_gm_proto_rawDesc = []byte{
	0x0a, 0x08, 0x67, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x61, 0x6d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22, 0x33, 0x0a, 0x0d, 0x47, 0x6d, 0x41, 0x64, 0x64,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x65, 0x73, 0x22, 0x47, 0x0a, 0x12,
	0x47, 0x6d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x72, 0x12, 0x31, 0x0a, 0x05, 0x61, 0x72, 0x65, 0x61, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x47, 0x61, 0x6d, 0x65, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05,
	0x61, 0x72, 0x65, 0x61, 0x73, 0x22, 0x40, 0x0a, 0x0e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x72, 0x65, 0x61, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x61, 0x72, 0x65, 0x61, 0x49, 0x64,
	0x12, 0x15, 0x0a, 0x06, 0x62, 0x75, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d,
	0x52, 0x05, 0x62, 0x75, 0x73, 0x49, 0x64, 0x42, 0x10, 0x5a, 0x0e, 0x61, 0x6d, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x69, 0x6e,
}

var (
	file_gm_proto_rawDescOnce sync.Once
	file_gm_proto_rawDescData = file_gm_proto_rawDesc
)

func file_gm_proto_rawDescGZIP() []byte {
	file_gm_proto_rawDescOnce.Do(func() {
		file_gm_proto_rawDescData = protoimpl.X.CompressGZIP(file_gm_proto_rawDescData)
	})
	return file_gm_proto_rawDescData
}

var file_gm_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gm_proto_goTypes = []interface{}{
	(*GmAddResource)(nil),      // 0: am.protocol.GmAddResource
	(*GmUpdateGameRouter)(nil), // 1: am.protocol.GmUpdateGameRouter
	(*GameRouterInfo)(nil),     // 2: am.protocol.GameRouterInfo
}
var file_gm_proto_depIdxs = []int32{
	2, // 0: am.protocol.GmUpdateGameRouter.areas:type_name -> am.protocol.GameRouterInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gm_proto_init() }
func file_gm_proto_init() {
	if File_gm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GmAddResource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GmUpdateGameRouter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameRouterInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gm_proto_goTypes,
		DependencyIndexes: file_gm_proto_depIdxs,
		MessageInfos:      file_gm_proto_msgTypes,
	}.Build()
	File_gm_proto = out.File
	file_gm_proto_rawDesc = nil
	file_gm_proto_goTypes = nil
	file_gm_proto_depIdxs = nil
}
