// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: in_battle.proto

package in

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SB_TakeRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StageId *uint32  `protobuf:"varint,1,opt,name=stage_id,json=stageId" json:"stage_id,omitempty"`
	RoomId  *uint64  `protobuf:"varint,2,opt,name=room_id,json=roomId" json:"room_id,omitempty"`
	Uids    []uint64 `protobuf:"varint,3,rep,name=uids" json:"uids,omitempty"`
}

func (x *SB_TakeRoom) Reset() {
	*x = SB_TakeRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_in_battle_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SB_TakeRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SB_TakeRoom) ProtoMessage() {}

func (x *SB_TakeRoom) ProtoReflect() protoreflect.Message {
	mi := &file_in_battle_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SB_TakeRoom.ProtoReflect.Descriptor instead.
func (*SB_TakeRoom) Descriptor() ([]byte, []int) {
	return file_in_battle_proto_rawDescGZIP(), []int{0}
}

func (x *SB_TakeRoom) GetStageId() uint32 {
	if x != nil && x.StageId != nil {
		return *x.StageId
	}
	return 0
}

func (x *SB_TakeRoom) GetRoomId() uint64 {
	if x != nil && x.RoomId != nil {
		return *x.RoomId
	}
	return 0
}

func (x *SB_TakeRoom) GetUids() []uint64 {
	if x != nil {
		return x.Uids
	}
	return nil
}

type BS_TakeRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StageId *uint32  `protobuf:"varint,1,opt,name=stage_id,json=stageId" json:"stage_id,omitempty"`
	RoomId  *uint64  `protobuf:"varint,2,opt,name=room_id,json=roomId" json:"room_id,omitempty"`
	Uids    []uint64 `protobuf:"varint,3,rep,name=uids" json:"uids,omitempty"`
	Address *string  `protobuf:"bytes,4,opt,name=address" json:"address,omitempty"` //对客户端的监听地址
	Ok      *bool    `protobuf:"varint,5,opt,name=ok" json:"ok,omitempty"`
}

func (x *BS_TakeRoom) Reset() {
	*x = BS_TakeRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_in_battle_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BS_TakeRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BS_TakeRoom) ProtoMessage() {}

func (x *BS_TakeRoom) ProtoReflect() protoreflect.Message {
	mi := &file_in_battle_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BS_TakeRoom.ProtoReflect.Descriptor instead.
func (*BS_TakeRoom) Descriptor() ([]byte, []int) {
	return file_in_battle_proto_rawDescGZIP(), []int{1}
}

func (x *BS_TakeRoom) GetStageId() uint32 {
	if x != nil && x.StageId != nil {
		return *x.StageId
	}
	return 0
}

func (x *BS_TakeRoom) GetRoomId() uint64 {
	if x != nil && x.RoomId != nil {
		return *x.RoomId
	}
	return 0
}

func (x *BS_TakeRoom) GetUids() []uint64 {
	if x != nil {
		return x.Uids
	}
	return nil
}

func (x *BS_TakeRoom) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *BS_TakeRoom) GetOk() bool {
	if x != nil && x.Ok != nil {
		return *x.Ok
	}
	return false
}

var File_in_battle_proto protoreflect.FileDescriptor

var file_in_battle_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x69, 0x6e, 0x5f, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0b, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22, 0x55,
	0x0a, 0x0b, 0x53, 0x42, 0x5f, 0x54, 0x61, 0x6b, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x19, 0x0a,
	0x08, 0x73, 0x74, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x07, 0x73, 0x74, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x04, 0x52,
	0x04, 0x75, 0x69, 0x64, 0x73, 0x22, 0x7f, 0x0a, 0x0b, 0x42, 0x53, 0x5f, 0x54, 0x61, 0x6b, 0x65,
	0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x74, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12,
	0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x69, 0x64, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x04, 0x52, 0x04, 0x75, 0x69, 0x64, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x42, 0x10, 0x5a, 0x0e, 0x61, 0x6d, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x69, 0x6e,
}

var (
	file_in_battle_proto_rawDescOnce sync.Once
	file_in_battle_proto_rawDescData = file_in_battle_proto_rawDesc
)

func file_in_battle_proto_rawDescGZIP() []byte {
	file_in_battle_proto_rawDescOnce.Do(func() {
		file_in_battle_proto_rawDescData = protoimpl.X.CompressGZIP(file_in_battle_proto_rawDescData)
	})
	return file_in_battle_proto_rawDescData
}

var file_in_battle_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_in_battle_proto_goTypes = []interface{}{
	(*SB_TakeRoom)(nil), // 0: am.protocol.SB_TakeRoom
	(*BS_TakeRoom)(nil), // 1: am.protocol.BS_TakeRoom
}
var file_in_battle_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_in_battle_proto_init() }
func file_in_battle_proto_init() {
	if File_in_battle_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_in_battle_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SB_TakeRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_in_battle_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BS_TakeRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_in_battle_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_in_battle_proto_goTypes,
		DependencyIndexes: file_in_battle_proto_depIdxs,
		MessageInfos:      file_in_battle_proto_msgTypes,
	}.Build()
	File_in_battle_proto = out.File
	file_in_battle_proto_rawDesc = nil
	file_in_battle_proto_goTypes = nil
	file_in_battle_proto_depIdxs = nil
}
