// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: in_guild.proto

package in

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//获取公会列表
type GuildSync struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List     []*InGuildInfo `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	Operate  *string        `protobuf:"bytes,2,opt,name=operate" json:"operate,omitempty"`
	PlayerId *uint64        `protobuf:"varint,3,opt,name=playerId" json:"playerId,omitempty"` // 操作的uid , 审核通过、踢掉等
}

func (x *GuildSync) Reset() {
	*x = GuildSync{}
	if protoimpl.UnsafeEnabled {
		mi := &file_in_guild_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildSync) ProtoMessage() {}

func (x *GuildSync) ProtoReflect() protoreflect.Message {
	mi := &file_in_guild_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildSync.ProtoReflect.Descriptor instead.
func (*GuildSync) Descriptor() ([]byte, []int) {
	return file_in_guild_proto_rawDescGZIP(), []int{0}
}

func (x *GuildSync) GetList() []*InGuildInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GuildSync) GetOperate() string {
	if x != nil && x.Operate != nil {
		return *x.Operate
	}
	return ""
}

func (x *GuildSync) GetPlayerId() uint64 {
	if x != nil && x.PlayerId != nil {
		return *x.PlayerId
	}
	return 0
}

type InGuildInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      *uint64  `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Name    *string  `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Leader  *uint64  `protobuf:"varint,3,opt,name=Leader" json:"Leader,omitempty"`
	Level   *uint32  `protobuf:"varint,4,opt,name=Level" json:"Level,omitempty"`
	Member  []uint64 `protobuf:"varint,5,rep,name=member" json:"member,omitempty"`  //成员
	Apply   []uint64 `protobuf:"varint,6,rep,name=apply" json:"apply,omitempty"`    //加入申请
	Message *string  `protobuf:"bytes,7,opt,name=message" json:"message,omitempty"` //公会公告
}

func (x *InGuildInfo) Reset() {
	*x = InGuildInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_in_guild_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InGuildInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InGuildInfo) ProtoMessage() {}

func (x *InGuildInfo) ProtoReflect() protoreflect.Message {
	mi := &file_in_guild_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InGuildInfo.ProtoReflect.Descriptor instead.
func (*InGuildInfo) Descriptor() ([]byte, []int) {
	return file_in_guild_proto_rawDescGZIP(), []int{1}
}

func (x *InGuildInfo) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *InGuildInfo) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *InGuildInfo) GetLeader() uint64 {
	if x != nil && x.Leader != nil {
		return *x.Leader
	}
	return 0
}

func (x *InGuildInfo) GetLevel() uint32 {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return 0
}

func (x *InGuildInfo) GetMember() []uint64 {
	if x != nil {
		return x.Member
	}
	return nil
}

func (x *InGuildInfo) GetApply() []uint64 {
	if x != nil {
		return x.Apply
	}
	return nil
}

func (x *InGuildInfo) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

//创建公会 client -> game -> guild -> sync
type GuildCreate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`      //公会名字
	Leader *uint64 `protobuf:"varint,2,opt,name=leader" json:"leader,omitempty"` //会长uid
}

func (x *GuildCreate) Reset() {
	*x = GuildCreate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_in_guild_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildCreate) ProtoMessage() {}

func (x *GuildCreate) ProtoReflect() protoreflect.Message {
	mi := &file_in_guild_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildCreate.ProtoReflect.Descriptor instead.
func (*GuildCreate) Descriptor() ([]byte, []int) {
	return file_in_guild_proto_rawDescGZIP(), []int{2}
}

func (x *GuildCreate) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *GuildCreate) GetLeader() uint64 {
	if x != nil && x.Leader != nil {
		return *x.Leader
	}
	return 0
}

//解散公会 client -> game -> guild -> sync
type GuildDismiss struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildId *uint64 `protobuf:"varint,1,opt,name=guild_id,json=guildId" json:"guild_id,omitempty"`
}

func (x *GuildDismiss) Reset() {
	*x = GuildDismiss{}
	if protoimpl.UnsafeEnabled {
		mi := &file_in_guild_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildDismiss) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildDismiss) ProtoMessage() {}

func (x *GuildDismiss) ProtoReflect() protoreflect.Message {
	mi := &file_in_guild_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildDismiss.ProtoReflect.Descriptor instead.
func (*GuildDismiss) Descriptor() ([]byte, []int) {
	return file_in_guild_proto_rawDescGZIP(), []int{3}
}

func (x *GuildDismiss) GetGuildId() uint64 {
	if x != nil && x.GuildId != nil {
		return *x.GuildId
	}
	return 0
}

//申请加入公会 client -> game -> guild -> game(leader)
type GuildApplyJoin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildId *uint64 `protobuf:"varint,1,opt,name=guild_id,json=guildId" json:"guild_id,omitempty"`
	Applier *uint64 `protobuf:"varint,2,opt,name=applier" json:"applier,omitempty"` //申请加入的player uid
}

func (x *GuildApplyJoin) Reset() {
	*x = GuildApplyJoin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_in_guild_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildApplyJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildApplyJoin) ProtoMessage() {}

func (x *GuildApplyJoin) ProtoReflect() protoreflect.Message {
	mi := &file_in_guild_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildApplyJoin.ProtoReflect.Descriptor instead.
func (*GuildApplyJoin) Descriptor() ([]byte, []int) {
	return file_in_guild_proto_rawDescGZIP(), []int{4}
}

func (x *GuildApplyJoin) GetGuildId() uint64 {
	if x != nil && x.GuildId != nil {
		return *x.GuildId
	}
	return 0
}

func (x *GuildApplyJoin) GetApplier() uint64 {
	if x != nil && x.Applier != nil {
		return *x.Applier
	}
	return 0
}

//公会加入申请审核 client -> game -> guild -> （通过）sync + apply zone
type GuildApplyCheck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildId *uint64 `protobuf:"varint,1,opt,name=guild_id,json=guildId" json:"guild_id,omitempty"`
	Applier *uint64 `protobuf:"varint,2,opt,name=applier" json:"applier,omitempty"` //加入的玩家uid
	Accept  *uint32 `protobuf:"varint,3,opt,name=accept" json:"accept,omitempty"`   //审核是否通过 1 通过 0 未通过
}

func (x *GuildApplyCheck) Reset() {
	*x = GuildApplyCheck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_in_guild_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildApplyCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildApplyCheck) ProtoMessage() {}

func (x *GuildApplyCheck) ProtoReflect() protoreflect.Message {
	mi := &file_in_guild_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildApplyCheck.ProtoReflect.Descriptor instead.
func (*GuildApplyCheck) Descriptor() ([]byte, []int) {
	return file_in_guild_proto_rawDescGZIP(), []int{5}
}

func (x *GuildApplyCheck) GetGuildId() uint64 {
	if x != nil && x.GuildId != nil {
		return *x.GuildId
	}
	return 0
}

func (x *GuildApplyCheck) GetApplier() uint64 {
	if x != nil && x.Applier != nil {
		return *x.Applier
	}
	return 0
}

func (x *GuildApplyCheck) GetAccept() uint32 {
	if x != nil && x.Accept != nil {
		return *x.Accept
	}
	return 0
}

//退会 client -> game（删除user.guild） -> guild -> sync
type GuildLeave struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildId  *uint64 `protobuf:"varint,1,opt,name=guild_id,json=guildId" json:"guild_id,omitempty"`
	PlayerId *uint64 `protobuf:"varint,2,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
}

func (x *GuildLeave) Reset() {
	*x = GuildLeave{}
	if protoimpl.UnsafeEnabled {
		mi := &file_in_guild_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildLeave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildLeave) ProtoMessage() {}

func (x *GuildLeave) ProtoReflect() protoreflect.Message {
	mi := &file_in_guild_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildLeave.ProtoReflect.Descriptor instead.
func (*GuildLeave) Descriptor() ([]byte, []int) {
	return file_in_guild_proto_rawDescGZIP(), []int{6}
}

func (x *GuildLeave) GetGuildId() uint64 {
	if x != nil && x.GuildId != nil {
		return *x.GuildId
	}
	return 0
}

func (x *GuildLeave) GetPlayerId() uint64 {
	if x != nil && x.PlayerId != nil {
		return *x.PlayerId
	}
	return 0
}

//踢人 client -> game -> guild -> game(player的zone) -> sync
type GuildKick struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildId  *uint64 `protobuf:"varint,1,opt,name=guild_id,json=guildId" json:"guild_id,omitempty"`
	PlayerId *uint64 `protobuf:"varint,2,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
}

func (x *GuildKick) Reset() {
	*x = GuildKick{}
	if protoimpl.UnsafeEnabled {
		mi := &file_in_guild_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildKick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildKick) ProtoMessage() {}

func (x *GuildKick) ProtoReflect() protoreflect.Message {
	mi := &file_in_guild_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildKick.ProtoReflect.Descriptor instead.
func (*GuildKick) Descriptor() ([]byte, []int) {
	return file_in_guild_proto_rawDescGZIP(), []int{7}
}

func (x *GuildKick) GetGuildId() uint64 {
	if x != nil && x.GuildId != nil {
		return *x.GuildId
	}
	return 0
}

func (x *GuildKick) GetPlayerId() uint64 {
	if x != nil && x.PlayerId != nil {
		return *x.PlayerId
	}
	return 0
}

//修改公告 client -> game -> guild -> sync
type GuildMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildId *uint64 `protobuf:"varint,1,opt,name=guild_id,json=guildId" json:"guild_id,omitempty"`
	Message *string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (x *GuildMessage) Reset() {
	*x = GuildMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_in_guild_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildMessage) ProtoMessage() {}

func (x *GuildMessage) ProtoReflect() protoreflect.Message {
	mi := &file_in_guild_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildMessage.ProtoReflect.Descriptor instead.
func (*GuildMessage) Descriptor() ([]byte, []int) {
	return file_in_guild_proto_rawDescGZIP(), []int{8}
}

func (x *GuildMessage) GetGuildId() uint64 {
	if x != nil && x.GuildId != nil {
		return *x.GuildId
	}
	return 0
}

func (x *GuildMessage) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

var File_in_guild_proto protoreflect.FileDescriptor

var file_in_guild_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x69, 0x6e, 0x5f, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0b, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22, 0x6f, 0x0a,
	0x09, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x2c, 0x0a, 0x04, 0x4c, 0x69,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x6d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x49, 0x6e, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x22, 0xa7,
	0x01, 0x0a, 0x0b, 0x49, 0x6e, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x65,
	0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x05, 0x20, 0x03, 0x28, 0x04,
	0x52, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x6c,
	0x79, 0x18, 0x06, 0x20, 0x03, 0x28, 0x04, 0x52, 0x05, 0x61, 0x70, 0x70, 0x6c, 0x79, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x39, 0x0a, 0x0b, 0x47, 0x75, 0x69, 0x6c,
	0x64, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6c,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6c, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x22, 0x29, 0x0a, 0x0c, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x44, 0x69, 0x73, 0x6d,
	0x69, 0x73, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x22, 0x45,
	0x0a, 0x0e, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x4a, 0x6f, 0x69, 0x6e,
	0x12, 0x19, 0x0a, 0x08, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x07, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x61, 0x70,
	0x70, 0x6c, 0x69, 0x65, 0x72, 0x22, 0x5e, 0x0a, 0x0f, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x41, 0x70,
	0x70, 0x6c, 0x79, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x75, 0x69, 0x6c,
	0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x67, 0x75, 0x69, 0x6c,
	0x64, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x61,
	0x63, 0x63, 0x65, 0x70, 0x74, 0x22, 0x44, 0x0a, 0x0a, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x4c, 0x65,
	0x61, 0x76, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x22, 0x43, 0x0a, 0x09, 0x47,
	0x75, 0x69, 0x6c, 0x64, 0x4b, 0x69, 0x63, 0x6b, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x75, 0x69, 0x6c,
	0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x67, 0x75, 0x69, 0x6c,
	0x64, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64,
	0x22, 0x43, 0x0a, 0x0c, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x19, 0x0a, 0x08, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x07, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x10, 0x5a, 0x0e, 0x61, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x69, 0x6e,
}

var (
	file_in_guild_proto_rawDescOnce sync.Once
	file_in_guild_proto_rawDescData = file_in_guild_proto_rawDesc
)

func file_in_guild_proto_rawDescGZIP() []byte {
	file_in_guild_proto_rawDescOnce.Do(func() {
		file_in_guild_proto_rawDescData = protoimpl.X.CompressGZIP(file_in_guild_proto_rawDescData)
	})
	return file_in_guild_proto_rawDescData
}

var file_in_guild_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_in_guild_proto_goTypes = []interface{}{
	(*GuildSync)(nil),       // 0: am.protocol.GuildSync
	(*InGuildInfo)(nil),     // 1: am.protocol.InGuildInfo
	(*GuildCreate)(nil),     // 2: am.protocol.GuildCreate
	(*GuildDismiss)(nil),    // 3: am.protocol.GuildDismiss
	(*GuildApplyJoin)(nil),  // 4: am.protocol.GuildApplyJoin
	(*GuildApplyCheck)(nil), // 5: am.protocol.GuildApplyCheck
	(*GuildLeave)(nil),      // 6: am.protocol.GuildLeave
	(*GuildKick)(nil),       // 7: am.protocol.GuildKick
	(*GuildMessage)(nil),    // 8: am.protocol.GuildMessage
}
var file_in_guild_proto_depIdxs = []int32{
	1, // 0: am.protocol.GuildSync.List:type_name -> am.protocol.InGuildInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_in_guild_proto_init() }
func file_in_guild_proto_init() {
	if File_in_guild_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_in_guild_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuildSync); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_in_guild_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InGuildInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_in_guild_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuildCreate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_in_guild_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuildDismiss); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_in_guild_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuildApplyJoin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_in_guild_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuildApplyCheck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_in_guild_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuildLeave); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_in_guild_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuildKick); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_in_guild_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuildMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_in_guild_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_in_guild_proto_goTypes,
		DependencyIndexes: file_in_guild_proto_depIdxs,
		MessageInfos:      file_in_guild_proto_msgTypes,
	}.Build()
	File_in_guild_proto = out.File
	file_in_guild_proto_rawDesc = nil
	file_in_guild_proto_goTypes = nil
	file_in_guild_proto_depIdxs = nil
}
