// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: in_login.proto

package in

import (
	out "github.com/Lei2050/game_server/protocol/out"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Kickoff struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason *out.KickoffReason `protobuf:"varint,1,opt,name=reason,enum=am.protocol.KickoffReason" json:"reason,omitempty"`
	GwId   *uint32            `protobuf:"varint,2,opt,name=gw_id,json=gwId" json:"gw_id,omitempty"` //网关的连接id
}

func (x *Kickoff) Reset() {
	*x = Kickoff{}
	if protoimpl.UnsafeEnabled {
		mi := &file_in_login_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Kickoff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kickoff) ProtoMessage() {}

func (x *Kickoff) ProtoReflect() protoreflect.Message {
	mi := &file_in_login_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kickoff.ProtoReflect.Descriptor instead.
func (*Kickoff) Descriptor() ([]byte, []int) {
	return file_in_login_proto_rawDescGZIP(), []int{0}
}

func (x *Kickoff) GetReason() out.KickoffReason {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return out.KickoffReason(0)
}

func (x *Kickoff) GetGwId() uint32 {
	if x != nil && x.GwId != nil {
		return *x.GwId
	}
	return 0
}

//网关的客户端连接断开
type GatewayConnClose struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GatewayConnClose) Reset() {
	*x = GatewayConnClose{}
	if protoimpl.UnsafeEnabled {
		mi := &file_in_login_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayConnClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayConnClose) ProtoMessage() {}

func (x *GatewayConnClose) ProtoReflect() protoreflect.Message {
	mi := &file_in_login_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayConnClose.ProtoReflect.Descriptor instead.
func (*GatewayConnClose) Descriptor() ([]byte, []int) {
	return file_in_login_proto_rawDescGZIP(), []int{1}
}

var File_in_login_proto protoreflect.FileDescriptor

var file_in_login_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x69, 0x6e, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0b, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x1a, 0x0b, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x52, 0x0a, 0x07, 0x4b, 0x69,
	0x63, 0x6b, 0x6f, 0x66, 0x66, 0x12, 0x32, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x4b, 0x69, 0x63, 0x6b, 0x6f, 0x66, 0x66, 0x52, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x13, 0x0a, 0x05, 0x67, 0x77, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x67, 0x77, 0x49, 0x64, 0x22, 0x12,
	0x0a, 0x10, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x43, 0x6f, 0x6e, 0x6e, 0x43, 0x6c, 0x6f,
	0x73, 0x65, 0x42, 0x10, 0x5a, 0x0e, 0x61, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2f, 0x69, 0x6e,
}

var (
	file_in_login_proto_rawDescOnce sync.Once
	file_in_login_proto_rawDescData = file_in_login_proto_rawDesc
)

func file_in_login_proto_rawDescGZIP() []byte {
	file_in_login_proto_rawDescOnce.Do(func() {
		file_in_login_proto_rawDescData = protoimpl.X.CompressGZIP(file_in_login_proto_rawDescData)
	})
	return file_in_login_proto_rawDescData
}

var file_in_login_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_in_login_proto_goTypes = []interface{}{
	(*Kickoff)(nil),          // 0: am.protocol.Kickoff
	(*GatewayConnClose)(nil), // 1: am.protocol.GatewayConnClose
	(out.KickoffReason)(0),   // 2: am.protocol.KickoffReason
}
var file_in_login_proto_depIdxs = []int32{
	2, // 0: am.protocol.Kickoff.reason:type_name -> am.protocol.KickoffReason
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_in_login_proto_init() }
func file_in_login_proto_init() {
	if File_in_login_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_in_login_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Kickoff); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_in_login_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayConnClose); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_in_login_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_in_login_proto_goTypes,
		DependencyIndexes: file_in_login_proto_depIdxs,
		MessageInfos:      file_in_login_proto_msgTypes,
	}.Build()
	File_in_login_proto = out.File
	file_in_login_proto_rawDesc = nil
	file_in_login_proto_goTypes = nil
	file_in_login_proto_depIdxs = nil
}
