// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: in_router.proto

package in

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RouterChooseType int32

const (
	RouterChooseType_RANDOM       RouterChooseType = 1 //随机选择
	RouterChooseType_LOWEST_LOAD  RouterChooseType = 2 //负载最低
	RouterChooseType_HIGHEST_LOAD RouterChooseType = 3 //负载最高
)

// Enum value maps for RouterChooseType.
var (
	RouterChooseType_name = map[int32]string{
		1: "RANDOM",
		2: "LOWEST_LOAD",
		3: "HIGHEST_LOAD",
	}
	RouterChooseType_value = map[string]int32{
		"RANDOM":       1,
		"LOWEST_LOAD":  2,
		"HIGHEST_LOAD": 3,
	}
)

func (x RouterChooseType) Enum() *RouterChooseType {
	p := new(RouterChooseType)
	*p = x
	return p
}

func (x RouterChooseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RouterChooseType) Descriptor() protoreflect.EnumDescriptor {
	return file_in_router_proto_enumTypes[0].Descriptor()
}

func (RouterChooseType) Type() protoreflect.EnumType {
	return &file_in_router_proto_enumTypes[0]
}

func (x RouterChooseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RouterChooseType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RouterChooseType(num)
	return nil
}

// Deprecated: Use RouterChooseType.Descriptor instead.
func (RouterChooseType) EnumDescriptor() ([]byte, []int) {
	return file_in_router_proto_rawDescGZIP(), []int{0}
}

type RouterReportInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CpuRate *float32 `protobuf:"fixed32,1,opt,name=cpu_rate,json=cpuRate" json:"cpu_rate,omitempty"` //cpu使用率
	MemRate *float32 `protobuf:"fixed32,2,opt,name=mem_rate,json=memRate" json:"mem_rate,omitempty"` //内存使用率，先不考虑虚拟内存
}

func (x *RouterReportInfo) Reset() {
	*x = RouterReportInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_in_router_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouterReportInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouterReportInfo) ProtoMessage() {}

func (x *RouterReportInfo) ProtoReflect() protoreflect.Message {
	mi := &file_in_router_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouterReportInfo.ProtoReflect.Descriptor instead.
func (*RouterReportInfo) Descriptor() ([]byte, []int) {
	return file_in_router_proto_rawDescGZIP(), []int{0}
}

func (x *RouterReportInfo) GetCpuRate() float32 {
	if x != nil && x.CpuRate != nil {
		return *x.CpuRate
	}
	return 0
}

func (x *RouterReportInfo) GetMemRate() float32 {
	if x != nil && x.MemRate != nil {
		return *x.MemRate
	}
	return 0
}

type RouterNodeReport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BusId *uint32           `protobuf:"varint,1,opt,name=bus_id,json=busId" json:"bus_id,omitempty"`
	Info  *RouterReportInfo `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
}

func (x *RouterNodeReport) Reset() {
	*x = RouterNodeReport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_in_router_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouterNodeReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouterNodeReport) ProtoMessage() {}

func (x *RouterNodeReport) ProtoReflect() protoreflect.Message {
	mi := &file_in_router_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouterNodeReport.ProtoReflect.Descriptor instead.
func (*RouterNodeReport) Descriptor() ([]byte, []int) {
	return file_in_router_proto_rawDescGZIP(), []int{1}
}

func (x *RouterNodeReport) GetBusId() uint32 {
	if x != nil && x.BusId != nil {
		return *x.BusId
	}
	return 0
}

func (x *RouterNodeReport) GetInfo() *RouterReportInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

//对于有多个进程实例的app_type，需要选择其中一个进行业务。
//比如申请副本时，需要选择一个战斗服进行战斗。
type RouterChooseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type *RouterChooseType `protobuf:"varint,1,opt,name=type,enum=am.protocol.RouterChooseType,def=2" json:"type,omitempty"`
	Cmd  *uint32           `protobuf:"varint,2,opt,name=cmd" json:"cmd,omitempty"` //发起请求的是哪个指令
}

// Default values for RouterChooseRequest fields.
const (
	Default_RouterChooseRequest_Type = RouterChooseType_LOWEST_LOAD
)

func (x *RouterChooseRequest) Reset() {
	*x = RouterChooseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_in_router_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouterChooseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouterChooseRequest) ProtoMessage() {}

func (x *RouterChooseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_in_router_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouterChooseRequest.ProtoReflect.Descriptor instead.
func (*RouterChooseRequest) Descriptor() ([]byte, []int) {
	return file_in_router_proto_rawDescGZIP(), []int{2}
}

func (x *RouterChooseRequest) GetType() RouterChooseType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return Default_RouterChooseRequest_Type
}

func (x *RouterChooseRequest) GetCmd() uint32 {
	if x != nil && x.Cmd != nil {
		return *x.Cmd
	}
	return 0
}

type RouterChooseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BusId *uint32 `protobuf:"varint,1,opt,name=bus_id,json=busId" json:"bus_id,omitempty"`
	Cmd   *uint32 `protobuf:"varint,2,opt,name=cmd" json:"cmd,omitempty"` //发起请求的是哪个指令，用来判断后续逻辑
}

func (x *RouterChooseResponse) Reset() {
	*x = RouterChooseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_in_router_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouterChooseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouterChooseResponse) ProtoMessage() {}

func (x *RouterChooseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_in_router_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouterChooseResponse.ProtoReflect.Descriptor instead.
func (*RouterChooseResponse) Descriptor() ([]byte, []int) {
	return file_in_router_proto_rawDescGZIP(), []int{3}
}

func (x *RouterChooseResponse) GetBusId() uint32 {
	if x != nil && x.BusId != nil {
		return *x.BusId
	}
	return 0
}

func (x *RouterChooseResponse) GetCmd() uint32 {
	if x != nil && x.Cmd != nil {
		return *x.Cmd
	}
	return 0
}

var File_in_router_proto protoreflect.FileDescriptor

var file_in_router_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x69, 0x6e, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0b, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22, 0x48,
	0x0a, 0x10, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x70, 0x75, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x63, 0x70, 0x75, 0x52, 0x61, 0x74, 0x65, 0x12, 0x19, 0x0a,
	0x08, 0x6d, 0x65, 0x6d, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x07, 0x6d, 0x65, 0x6d, 0x52, 0x61, 0x74, 0x65, 0x22, 0x5c, 0x0a, 0x10, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x15, 0x0a, 0x06,
	0x62, 0x75, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x62, 0x75,
	0x73, 0x49, 0x64, 0x12, 0x31, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x67, 0x0a, 0x13, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72,
	0x43, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3e, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x61, 0x6d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72,
	0x43, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x3a, 0x0b, 0x4c, 0x4f, 0x57, 0x45,
	0x53, 0x54, 0x5f, 0x4c, 0x4f, 0x41, 0x44, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x63, 0x6d, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x22,
	0x3f, 0x0a, 0x14, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x43, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x62, 0x75, 0x73, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x62, 0x75, 0x73, 0x49, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x63, 0x6d, 0x64,
	0x2a, 0x41, 0x0a, 0x10, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x43, 0x68, 0x6f, 0x6f, 0x73, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x41, 0x4e, 0x44, 0x4f, 0x4d, 0x10, 0x01,
	0x12, 0x0f, 0x0a, 0x0b, 0x4c, 0x4f, 0x57, 0x45, 0x53, 0x54, 0x5f, 0x4c, 0x4f, 0x41, 0x44, 0x10,
	0x02, 0x12, 0x10, 0x0a, 0x0c, 0x48, 0x49, 0x47, 0x48, 0x45, 0x53, 0x54, 0x5f, 0x4c, 0x4f, 0x41,
	0x44, 0x10, 0x03, 0x42, 0x10, 0x5a, 0x0e, 0x61, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2f, 0x69, 0x6e,
}

var (
	file_in_router_proto_rawDescOnce sync.Once
	file_in_router_proto_rawDescData = file_in_router_proto_rawDesc
)

func file_in_router_proto_rawDescGZIP() []byte {
	file_in_router_proto_rawDescOnce.Do(func() {
		file_in_router_proto_rawDescData = protoimpl.X.CompressGZIP(file_in_router_proto_rawDescData)
	})
	return file_in_router_proto_rawDescData
}

var file_in_router_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_in_router_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_in_router_proto_goTypes = []interface{}{
	(RouterChooseType)(0),        // 0: am.protocol.RouterChooseType
	(*RouterReportInfo)(nil),     // 1: am.protocol.RouterReportInfo
	(*RouterNodeReport)(nil),     // 2: am.protocol.RouterNodeReport
	(*RouterChooseRequest)(nil),  // 3: am.protocol.RouterChooseRequest
	(*RouterChooseResponse)(nil), // 4: am.protocol.RouterChooseResponse
}
var file_in_router_proto_depIdxs = []int32{
	1, // 0: am.protocol.RouterNodeReport.info:type_name -> am.protocol.RouterReportInfo
	0, // 1: am.protocol.RouterChooseRequest.type:type_name -> am.protocol.RouterChooseType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_in_router_proto_init() }
func file_in_router_proto_init() {
	if File_in_router_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_in_router_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouterReportInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_in_router_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouterNodeReport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_in_router_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouterChooseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_in_router_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouterChooseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_in_router_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_in_router_proto_goTypes,
		DependencyIndexes: file_in_router_proto_depIdxs,
		EnumInfos:         file_in_router_proto_enumTypes,
		MessageInfos:      file_in_router_proto_msgTypes,
	}.Build()
	File_in_router_proto = out.File
	file_in_router_proto_rawDesc = nil
	file_in_router_proto_goTypes = nil
	file_in_router_proto_depIdxs = nil
}
